apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: shoppinglist-server
build:
  artifacts:
    - image: ghcr.io/kmjayadeep/shoppinglist-server
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s
