basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: shoppinglist.cosmos.cboxlab.com
info:
  contact: {}
  description: Shopping list manager
  title: Shopping List
  version: "1.0"
paths: {}
schemes:
- https
swagger: "2.0"
